### PR TITLE
cropped individual images of alphabets for web version

### PR DESCRIPTION
**Pull request by Siddharth1006**
I cropped excess parts of the image of the alphabet so that, when we combine the letters to form words/sentences, it feels more natural, less space is used.
This is my proposed solution for Issue #10 ==> Gap between letters

### CODE REVIEW

**Review by ghanender-chauhan — CHANGES_REQUESTED** [review]
No this is not accepted try to write a programme which decrease the spaces between the letters.

**Comment by Siddharth1006** [comment]
> No this is not accepted try to write a programme which decrease the spaces between the letters.

I wrote a program using crop function from Pillow module and then cropped the images..

This is my code:

from PIL import Image 
original = Image.open(r"Path to the image") 
  
width, height = original.size
x = 0
y = 0
x1 = width / 2
y1 = height / 4 * 3

im = original.crop((x , y , x1 , y1)) 
im.show()

**Comment by Siddharth1006** [comment]
> No this is not accepted try to write a programme which decrease the spaces between the letters.

Do you want the function to be implemented within the code??

**Comment by av1shek** [comment]
> No this is not accepted try to write a programm which decrease the spaces between the letters.

I guess cropping is also required, because all images are not uniform so we can not hide extra part of that letter or 
even if we write code then we have to give different coordintes for different letters manually unless and until we not use any Machine learning Model to detect the character.

And using ML model just to add it only once is not good idea,

**Comment by Siddharth1006** [comment]
> > No this is not accepted try to write a programm which decrease the spaces between the letters.
> 
> I guess cropping is also required, because all images are not uniform so we can not hide extra part of that letter or
> even if we write code then we have to give different coordintes for different letters manually unless and until we not use any Machine learning Model to detect the character.
> 
> And using ML model just to add it only once is not good idea,

You also tried solving this issue? how did u approach? I think u did the same as what i did if i am not wrong?

**Comment by ghanender-chauhan** [comment]
> > No this is not accepted try to write a programme which decrease the spaces between the letters.
> 
> I wrote a program using crop function from Pillow module and then cropped the images..
> 
> This is my code:
> 
> from PIL import Image
> original = Image.open(r"Path to the image")
> 
> width, height = original.size
> x = 0
> y = 0
> x1 = width / 2
> y1 = height / 4 * 3
> 
> im = original.crop((x , y , x1 , y1))
> im.show()

Ok I will look into your PR

**Pull request merged**
